#
# Hugo configuration file
#
baseURL = "https://seismo-learn.org/links/"
languageCode = "en-us"
title = "Seismo Links"
copyright = "&copy; Copyright 2018 - {year}, [seismo-learn](https://seismo-learn.org/). </br> [Contributions](https://github.com/seismo-learn/links#contributing) are welcomed."
disableKinds = [ "taxonomyTerm", "RSS" ]
enableGitInfo = true

[params]
lastupdate = "Built by [Hugo](https://gohugo.io/) on {now}."

  [params.assets]
  bootstrap_cdn = "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap"
  bootstrap_version = "4.6.0"
  bootswatch_cdn = "https://cdnjs.cloudflare.com/ajax/libs/bootswatch"
  bootswatch_version = "4.6.0"
  bootswatch_theme = "cosmo"
  fontawesome_cdn = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome"
  fontawesome_version = "5.15.3"
  jquery_cdn = "https://cdnjs.cloudflare.com/ajax/libs/jquery"
  jquery_version = "3.6.0"

  [params.edit_page]
  repo_url = "https://github.com/seismo-learn/links"
  branch = "main"
  edit_mode = "edit"
  repo_dir = "content"
  edit_text = ""

[markup.goldmark.renderer]
  unsafe = true
  [markup.tableOfContents]
    ordered = false
    startLevel = 2
    endLevel = 2

[[menu.main]]
  name = '<i class="fas fa-home"></i>'
  url = "/"
  weight = 10

[[menu.main]]
  name = '<i class="fab fa-github"></i>'
  url = "https://github.com/seismo-learn/links"
  weight = 40
