# This workflow checks the links in plaintext and HTML files
name: Check Links

on:
  # Uncomment the 'pull_request' line below to trigger the workflow in PR
  pull_request:
  # Schedule runs on 12 noon every Sunday
  schedule:
    - cron: '0 12 * * 0'

jobs:
  check_links:
    name: Check Links
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2.3.4
      with:
        path: repository

    - name: Checkout the website
      uses: actions/checkout@v2.3.4
      with:
        ref: gh-pages
        path: website

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.0.8
      with:
        # 429: Too many requests
        args: >
          --accept 429
          --exclude "http://localhost:1313/"
          --exclude "https://data.earthquake.cn/datashare/report.shtml?PAGEID=earthquake_lsdz"
          --exclude "http://www.kyoshin.bosai.go.jp/"
          --exclude "^https://www.fnet.bosai.go.jp/event/joho.php?LANG=en$"
          --exclude "http://www.earthmodels.org/"
          --exclude "^https://data.earthquake.cn/datashare/report.shtml?PAGEID=earthquake_zhengshi$"
          --exclude "http://www.fnet.bosai.go.jp/"
          --exclude "http://www.isgeoid.polimi.it/"
          --exclude "http://geophysics.geo.sunysb.edu/wen/resource/index.html"
          --exclude "^https://data.earthquake.cn/datashare/report.shtml?PAGEID=earthquake_zgtwzx$"
          --exclude "http://www.hinet.bosai.go.jp/"
          --exclude "^https://data.earthquake.cn/datashare/report.shtml?PAGEID=earthquake_gjtwzx$"
          --exclude "http://www.fnet.bosai.go.jp/event/joho.php?LANG=en"
          --exclude "http://www.hinet.bosai.go.jp/AQUA/aqua_catalogue.php?LANG=en"
          --exclude "https://www.scopus.com/home.uri"
          --exclude "http://geol.ckcest.cn/index.html"
          --verbose
          "repository/README.md"
          "website/**/*.html"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v3.0.0
      with:
        title: Link Checker Report
        content-filepath: ./lychee/out.md
